### ISSUE TITLE
1.0 Target Meta Issue

### ISSUE THREAD

**Issue by BosqueLanguage** [BosqueLanguage/BosqueCore#78]
Our 1.0 MVP target involves the following tasks:

- [x] Switch to BREX for Regex uses
- [ ] Switch to BSQON for object literals
- [ ] Update Core libs to match
- [ ] Cleanup front end to target MVP application (SMT checker)
- [ ] Move runtime to JS with/without write to files
